- name: Deploy Artifact to Localhost
  hosts: localhost
  tasks:
  - name: Copy the artifact to the target location
    become: true
    become_user: roshan
    become_method: su
    copy:
          src: "/var/lib/jenkins/workspace/pipe1/target/my-app-1.0-SNAPSHOT.jar"
          dest: "/home/roshan/t.jar"
